name: Build Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  lint-yml:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: ${{ github.workspace }}
            /.github/workflows/build-pipeline.yml

  compliance:
    needs: lint-yml
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/node-setup
      - name: NPM Audit
        uses: oke-py/npm-audit-action@v3.0.0
        with:
          issue_assignees: thkruz
          issue_labels: Security
          dedupe_issues: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  lint-and-test:
    needs: compliance
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [eslint, unit-test]
    steps:
      - uses: ./.github/actions/node-setup

      - name: Set Timezone
        if: matrix.task == 'unit-test'
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'America/New_York'

      - name: ESLint
        if: matrix.task == 'eslint'
        run: |
          echo "Running ESLint..."
          npx eslint . --ignore-path .gitignore --ext js,ts,tsx \
            | tee eslint-report.txt
          echo "### ESLint Summary" >> $GITHUB_STEP_SUMMARY
          tail -n 20 eslint-report.txt >> $GITHUB_STEP_SUMMARY

      - name: Unit Tests
        if: matrix.task == 'unit-test'
        run: |
          echo "Running Unit Tests..."
          npm test | tee test-report.txt
          echo "### Unit Test Summary" >> $GITHUB_STEP_SUMMARY
          tail -n 20 test-report.txt >> $GITHUB_STEP_SUMMARY

  build:
    needs: lint-and-test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/node-setup

      - name: Set up SSH for submodules
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          echo "Running Build..."
          npm run build
          echo "### Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "Build on $(date)" >> $GITHUB_STEP_SUMMARY

  trufflehog:
    needs: build
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.82.6
        continue-on-error: true

  codeql:
    needs: build
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3
